### ISSUE TITLE
Setup -> Enable shared NFS user home folder not available

### ISSUE THREAD

**Issue by pcm32** [TheNewNormal/kube-cluster-osx#91]
Hi there,

I recently reinstalled completely to be on the newest release. The NFS mount is not triggered any longer, and I don't get the menu item that allows to trigger the NFS mount of the /Users/myself on the VMs. This was a major feature for my use case of kube-cluster. Would it be possible to please fix/reinstate this?

Thanks!
Pablo

**Comment by rimusz** [comment]
hey @pcm32, we took it of as lot's of guys are having problems of booting VMs with NFS enabled by default.
But sure, I can make an option to enable/disable NFS as other apps have. Will see if I can find a spare time over weekend.
In the mean time you can use [kube-solo app](https://github.com/TheNewNormal/kube-solo-osx) which has the option to trigger NFS on/off

**Comment by pcm32** [comment]
Thanks @rimusz, that would be great! 

Actually, I just realised that using the previous settings left by the previous version on my /etc/exports, I can restart my nfsd and just call it from inside kubernetes through the NFS PersistentVolume... so no rush for me actually! But might serve others of course.

Just for the reference of other interested users, make sure that your /etc/exports has the following line:

```
/Users/<your_username> -network 192.168.64.0 -mask 255.255.255.0 -alldirs -maproot=root:wheel
```

and then restart your nfs daemon:

```
sudo nfsd restart
```

and then use a Persistent Volume that connects to this:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retained
  nfs:
    path: /Users/<your_username>/desired/path/to/mount
    server: 192.168.64.1
```

Put that on `pv_nfs.yml` and create the PV with `kubectl create -f pv_nfs.yml`. 

Then create a persistent volume claim that can use this, and then call that persistent volume claim in your pod/job/rc.
